# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Blockchain-Medical' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'BlueSocket'
  pod 'BlueSSLService'
  pod 'Charts'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firestore', :podspec => 'https://storage.googleapis.com/firebase-preview-drop/ios/firestore/0.7.0/Firestore.podspec.json'
  pod 'JSQMessagesViewController'
  pod 'CVCalendar', '~> 1.6.1'  
  # Pods for Blockchain-Medical

  target 'Blockchain-MedicalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Blockchain-MedicalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
