# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Blockchain-Medical' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'BlueSocket'
  pod 'BlueSSLService'
  pod 'Charts'
  
  # Pods for Blockchain-Medical

  target 'Blockchain-MedicalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Blockchain-MedicalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
